In [1]:
import pandas as pd
df = pd.read_csv('D:/credit_risk/data/processed/cleaned_data.csv')
df.head()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default
0,20000.0,2,2,1,24,2,2,-1,-1,-2,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,120000.0,2,2,2,26,-1,2,0,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,90000.0,2,2,2,34,0,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,50000.0,2,2,1,37,0,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,50000.0,1,2,1,57,-1,0,-1,0,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0

In [2]:
df['Late_Payments'] = (
    (df['PAY_0'] > 0).astype(int) +
    (df['PAY_2'] > 0).astype(int) +
    (df['PAY_3'] > 0).astype(int) +
    (df['PAY_4'] > 0).astype(int) +
    (df['PAY_5'] > 0).astype(int) +
    (df['PAY_6'] > 0).astype(int)
)
df['Late_Payments'].describe()

count    27524.000000
mean         0.837923
std          1.559278
min          0.000000
25%          0.000000
50%          0.000000
75%          1.000000
max          6.000000
Name: Late_Payments, dtype: float64

In [3]:
#identifying the risk by calculating the utilization ratio
df['Utilization'] = df['BILL_AMT1'] / df['LIMIT_BAL']
df['Utilization'].head()
df['Utilization'].describe()

count    27524.000000
mean         0.423960
std          0.411820
min         -0.619892
25%          0.022519
50%          0.314936
75%          0.828942
max          6.455300
Name: Utilization, dtype: float64

In [7]:
#creating the columns for total payment
df['Total_Payment'] = (
    df['PAY_AMT1'] +
    df['PAY_AMT2'] +
    df['PAY_AMT3'] +
    df['PAY_AMT4'] +
    df['PAY_AMT5'] +
    df['PAY_AMT6']
)

In [8]:
df['Total_Bill'] = (
    df['BILL_AMT1'] +
    df['BILL_AMT2'] +
    df['BILL_AMT3'] +
    df['BILL_AMT4'] +
    df['BILL_AMT5'] +
    df['BILL_AMT6']
)

In [9]:
df['Payment_Ratio'] = (
    df['Total_Payment'] /
    (df['Total_Bill'] + 1)
)

In [10]:
df['Age_Group'] = pd.cut(
    df['AGE'],
    bins=[20,30,40,50,80],
    labels=['20-30','30-40','40-50','50+']
)

In [11]:
df[
[
'Late_Payments',
'Utilization',
'Total_Bill',
'Total_Payment',
'Payment_Ratio'
]
].head()

   Late_Payments  Utilization  Total_Bill  Total_Payment  Payment_Ratio
0              2     0.195650      7704.0          689.0       0.089422
1              2     0.022350     17077.0         5000.0       0.292774
2              0     0.324878    101653.0        11018.0       0.108387
3              0     0.939800    231334.0         8388.0       0.036259
4              0     0.172340    109339.0        59049.0       0.540049

In [12]:
df.to_csv(
'D:/credit_risk/data/processed/final_credit_risk_data.csv',
index=False
)